[project]
name = "tsumemi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow==10.4",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pyinstaller==6.16.0",
    "pytest>=8.4.2",
    "ruff>=0.13.3",
]
